### PR TITLE
Support validation of nested objects (compound keys)

### PR DESCRIPTION
**Pull request by ivan-kleshnin**
Relatively complex one. I need this to have same state structure for detail and edit components (fields are under `model` key).
Please review commits from Feb 16, 2015
TODO: support immutable (see TODO in code)

### CODE REVIEW

**Comment by jurassix** [comment]
Nice! This could definitely be useful for other users. I'll review this PR tonight. I've finished the next API release candidate. I'll push it somewhere for conversation soon. It looks like there may be to many conflicts to use your branch; but I'll check.

**Comment by ivan-kleshnin** [comment]
I discovered more errors both in this code and in our expectations. Will update this PR as soon as possible.

**Comment by jurassix** [comment]
ok np

**Comment by ivan-kleshnin** [comment]
Closed in favor of https://github.com/jurassix/react-validation-mixin/pull/13

**Pull request closed without merging**
