### PR TITLE
Labels for error keys

### PR DESCRIPTION
**Pull request by ivan-kleshnin**
At this moment **react-validation-mixin** doesn't provide either helper or guidance on this.
I documented current approach to show how this may be done manually (via `Joi`, of course).
I also added handy method to auto pull labels from form fields to Joi validation scheme.
See updated documentation, please.

### CODE REVIEW

**Comment by jurassix** [comment]
Thanks for the pull request. 

Being able to scrap the form for custom labels is nice feature too. I agree custom labels needed documentation, that was in the works. 

I will add test to support your merge request and get this merged in soon.

**Comment by jurassix** [comment]
I've reviewed this pull request. I like the automated approach of pulling the label off the ref; pretty slick. 

I'm not sure about exposing the 'autoLabel' option, or the implementation of the automated labelt. I'd like to rework this implementation and back it by a front-end test harness. 

Can you modify this pull request to just include the documentation updates to the README around custom Joi labels? 

Then open a subsequent issue, and provide your autoLabel implementation. We can work towards getting this feature in.

Again, I think your idea is great, but the implementation and api around autoLabels needs to be a bigger conversation.

**Comment by ivan-kleshnin** [comment]
Sure, no problem.

**Comment by jurassix** [comment]
Thanks!
Published to npm as version 2.0.13

**Comment by jurassix** [comment]
oh...looks like I got the previous one pull merged in...Ok i'm backing out the changes to ValidationMixin and will release 2.0.14. Please open another issue for the autoLabel implementation. Thanks

**Pull request merged**
